# Generated by Django 6.0.4 on 2026-05-05 13:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='problem',
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': 'Тест-кейс', 'verbose_name_plural': 'Тест-кейсы'},
        ),
        migrations.AlterModelOptions(
            name='userproblemstatus',
            options={'verbose_name': 'Статус решения задачи', 'verbose_name_plural': 'Статусы решения задач'},
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='output_data',
            new_name='expected_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.TextField(default='', verbose_name='Условие задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproblemstatus',
            name='attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256, verbose_name='Ограничение по памяти (MB)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, verbose_name='Ограничение по времени (сек)'),
        ),
        migrations.AlterField(
            model_name='userproblemstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('solved', 'Решено')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('duration', models.IntegerField(help_text='Длительность в минутах', verbose_name='Длительность')),
                ('difficulty', models.CharField(default='medium', max_length=20, verbose_name='Сложность')),
                ('problems', models.ManyToManyField(blank=True, related_name='contests', to='tasks.problem', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('problems', models.ManyToManyField(blank=True, related_name='tags', to='tasks.problem')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contests_attended', models.IntegerField(default=0)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tasks.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
