# Generated by Django 6.0.5 on 2026-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_role_remove_problem_category_remove_hint_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblemstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('want', 'Хочу решить'), ('solved', 'Решено')], default='not_started', max_length=20),
        ),
    ]
